language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - "DISABLE_MIGRATE=true DISABLE_CREATE=true rake dummy:app"
  - "cp spec/support/application.txt spec/dummy/config/application.rb"  # hack to get around: https://travis-ci.org/twinge/questionnaire_engine/jobs/11889581
  - "cd spec/dummy && rails g qe:install && rake db:test:prepare && cd ../.."

# using default travis command
# script: bundle exec rake spec

branches:
  only:
    - engine
