language: ruby

rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - rake app:db:create
  - rake app:db:migrate
  - rake app:db:test:prepare

script:
  - bundle exec rake spec

after_script:
  -rake db:rollback
